### ISSUE TITLE
Apostrophes and font

### ISSUE THREAD

**Issue by Shoes01** [morgenman/SmartConvert#1]
First, I wanted to say thank you. I have been looking for a batch conversion script for a long time and this works!

The two issues I had were that apostrophes did not get read, and so they weren't converted. The other is that the font I used in the files did not get carried over to the pdf. 

I use Windows 7 and ran this through Cygwin. If you have any suggestions on what I can do to fix these, thanks! Otherwise, know that your script will be saving me a lot of time. Thanks again!

edit: Some pages are also getting cut off, normally losing half the last word. I will try this script in a proper Linux environment to see if I get the same problems.

**Comment by morgenman** [comment]
Let me know if the problems still exist, if you are testing on windows, try using the subsystem for linux, its a bit better than Cygwin. I will look into the issues myself when I get the chance

**Comment by Shoes01** [comment]
I'm going to close this issue as I have changed how I use .notebook files as to not need to convert so many files individually. Thanks again!

**Comment by morgenman** [comment]
No problem, glad it helped!
